services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: yam_report_api
    ports:
      - "3599:5000"
    env_file:
      - .env
    volumes:
      - yam-report-api-logs:/app/logs
    restart: unless-stopped
    networks:
      - yam-events-db-shared-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    container_name: yam_report_ui
    ports:
      - "3598:80"
    restart: unless-stopped

volumes:
  yam-report-api-logs:

networks:
  yam-events-db-shared-network:
    external: true