FROM nginx:latest

# Installer Node.js 18
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Créer et définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY UI/package*.json ./UI/

# Installer les dépendances Node.js
RUN cd UI && npm install

# Copier le reste du code source du frontend
COPY UI ./UI

# Construire le frontend
RUN cd UI && npm run build

# Copier le build dans le dossier nginx
RUN cp -r UI/dist/* /usr/share/nginx/html/

# Remove Node.js
RUN apt-get remove -y nodejs

# Exposer les ports nécessaires
EXPOSE 80