FROM node:20-alpine AS builder

WORKDIR /app
COPY UI/package*.json ./
RUN npm ci
COPY UI/ ./
RUN npm run build

FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/ /usr/share/nginx/html/
EXPOSE 80